### ISSUE TITLE
Keep user session

### ISSUE THREAD

**Issue by lesonunique** [wnabil/ngx-drupal7-services#25]
Hello,

I use the `systemService.connect()` function to keep a user session open but at times the user reconnects well and at other times the connection is not made and the user is forced to redo his connection (sessid and session_name are automatically replaced). I notice the concern about the ionic cordova version of the application and not about the browser

```
this.userService.token().toPromise()
      .then(res => {
            console.log(res);
            this.systemService.connect().toPromise()
                .then(connection => {
                     console.log(connection);
                     this.loadConnection(connection);
                 }).catch(err => {
                     console.log(err);
                });
      }).catch(err => {
          console.log(err);
     });
```

By doing different tests, I noticed that the requests /services/session/token and /system/connect are executed automatically when the application is launched even without calling `userService.token()` and `systemService.connect()`

Is there a way to not execute these requests at initialization so that it only executes it once the `systemService.connect()` function is called?

Thanks

**Comment by wnabil** [comment]
Hi,
What platform you are using ? and also please give more details about your system like android version and ionic version

**Comment by lesonunique** [comment]
Here is the information on the versions of Ionic 3 and Cordova. My application is also generated for iOS, but I first develop on Android (my tests are done on two phones under android 8.0 and android 9.0)

```
Ionic:

   ionic (Ionic CLI)  : 4.12.0 (C:\Users\membre\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.3
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-webview 2.2.3, (and 22 other plugins)

System:

   Android SDK Tools : 26.1.1 (H:\Android\sdk1)
   NodeJS            : v8.11.2 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Comment by wnabil** [comment]
Well i have to say if the session replaced this means the user got logged out.
The connection is made at first launch because i implemented `APP_INITIALIZER` in `ngx-drupal7-services.module.ts` file.
```javascript
/**
 * implement APP_INITIALIZER
 * @param systemService system service to connect
 * @see https://gillespie59.github.io/2016/12/04/angular2-code-before-rendering.html
 */
export function init(systemService: SystemService): () => Promise<SystemConnection> {
  return () => {
    const connectionObservable = systemService.connect(true).toPromise();
    return connectionObservable;
  };
}
```
As i described in [this issue](https://github.com/wnabil/ngx-drupal7-services/issues/1#issuecomment-355904506), You have to check for the session validation before letting the user continue using the application because the backend might expire the session and the user keeps working on the application.

So in fact what is happens on your application is the session is expired so the application fetches a new one, there is no control at the app level for the cookies to even change it at the runtime because drupal will use `set_cookie` header when the user authenticated.
Another issue on iOS might be happens as [described here](https://github.com/wnabil/ngx-drupal7-services/issues/21)

I suggest you to check your `settings.php` file and make sure the session time is configured well.

If you really found that the `APP_INITIALIZER` is your problem then you can do the following to stop the connection initialization request at first app launch:

1. Stop importing the library in `app.module.ts` file - remove `Drupal7ServicesModule` from imports array.
2. Create your own module that imports all the required services exactly as [this file here](https://github.com/wnabil/ngx-drupal7-services/blob/dev/projects/ngx-drupal7-services/src/lib/ngx-drupal7-services.module.ts) but without implementing `APP_INITIALIZER`
3. Finally import this module into your project

Keep in mind this way if the session expired at the backend, your app will never detect it and you have to handle it yourself.

**Comment by lesonunique** [comment]
I have the latest version in my project `ngx-drupal7-services": "^1.7.3"`

I did different tests, I tried to put the `systemService.connect()` function in my app.component.ts in execution at first just in the `platform.ready()` and `deviceready`. I always notice the problem, sometimes, once connected the reconnection works several times in a row, but at other times the reconnection no longer works and this several times in a row (without me being able to understand what makes this change).

On the other hand, I noticed in the Network logs a difference in both cases that explains the non-reconnection. Maybe this could be a lead to the source of the concern?

Below are the `token` and `connect` requests in both cases.

First time it works properly:

https://goopics.net/i/djYOw
https://goopics.net/i/wEV5R

Second case where reconnection does not work. We notice that the authentication value is `null=null` (whereas when the application is launched, I see the information of the previous sessid session and session_name which are in the localStorage but are quickly replaced by other values of the anonymous session).

https://goopics.net/i/P2awq
https://goopics.net/i/NZkeg

I would obviously prefer to keep the plugin running rather than redo the requests on drupal services and session storage "manually".

All my tests are on an Android device.

**Comment by wnabil** [comment]
Authentication header is not used anymore for authentication, this header was used as a temp solution for iOS WKWebView cookie sync issue and it requires a special code at the backend or Drupal will do nothing with it.
Drupal uses the cookie header for authentication and currently we are using the base Drupal concept to make the connection. However, The cookie header is set by Drupal when you do `user/login` and `system/connect` post request.
As i said there is no manual access anymore at the app side to manage the cookie so if the connection expired then yes Drupal will send you a new connection and expires the old one and the package for sure will save the new one because the old one expired, what i need from the old expired session?
If you are logged in and successfully authenticated it doesn't matter how many times you will request the token or connect resource, you will always get the same token and also the same session "If Drupal did not expires them" and you can check that your self by going to your website page, logging in and going to `services/session/token` and you will always get the same token until you logged out then you will start getting a different one each request.

I am very sure now the problem is your backend settings and to make sure you can upload me a demo project that have this issue and i can debug it, please also add for me a temp user at your website because i am going to test it with your backend, you can email me the username and the password at `w.nabil@orangestudio.com`

**Comment by lesonunique** [comment]
I sent you an email with these different elements.
In my settings.php, however, I notice these values which seem to indicate a rather long session duration.
```
ini_set('session.gc_maxlifetime', 2000000);
ini_set('session.cookie_lifetime', 2000000);
```
Maybe other settings are missing?
